version: '3.9'
services:
  node:
    image: sdc-node
    container_name: sdc-node
    depends_on:
      - mongo
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: node.Dockerfile
  mongo:
    image: mongo
    container_name: sdc-mongo
    ports: 
      - 3001:27017
    environment:
      MONGO_INITDB_DATABASE: sdc-questions
    build: 
      context: .
      dockerfile: mongo.Dockerfile
    volumes:
        - sdc-questions:/data/db
          # /docker-entrypoint-initdb.d
    # restart: unless-stopped
volumes:
  sdc-questions: